serverUrl: http://mywebsite.com
shortTitle: My Blog
title: My F# Blog
description: My ramblings and experiences with building stuff with F#
masterUserDisplayName: My Name
masterLanguage: en
languages: "en->English,es->Spanish,hu->Hungarian"
masterUserDisplayName: Akos Steiner
users: "akos->Akos Steiner,fred->Fred Smith,bill->Bill Smith"